version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: chat_nginx
    links:
      - app
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ".:/code"

  app:
    image: shufo/phoenix:1.3.4-development
    container_name: chat_app
    hostname: app
    expose:
      - 4000
    ports:
      - "4000:4000"
      - "4001:4001"
    working_dir: /code
    environment:
      - "PORT=4000"
    volumes:
      - ".:/code"
    links:
      - postgres
      - redis

  redis:
    image: redis:alpine
    container_name: chat_redis
    hostname: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    container_name: chat_postgres
    hostname: postgres
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=server_dev"
